inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Exclude:
    - "db/**/*"
    - "app/controllers/customer/webhooks_controller.rb"

Rails/I18nLocaleTexts:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

require:
  - rubocop-ast
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance
