default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.credentials.db[:database] %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>
  port: <%= Rails.application.credentials.db[:port] %>
  pool: <%= Rails.application.credentials.db[:pool] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
